spring:
  flyway:
    locations: db/migration
  datasource:
    url: jdbc:mysql://localhost:3306/mysql-demo?createDatabaseIfNotExist=true
    username: root
    password: 123456
    driverClassName: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: "classpath:repository/*.xml"
  configuration:
    map-underscore-to-camel-case: true